# Generated by Django 3.1 on 2020-09-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200920_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='giảm giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_list',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ảnh chi tiết'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug danh mục'),
        ),
    ]
