# Generated by Django 3.1 on 2020-09-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200923_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
    ]
