# Generated by Django 3.1 on 2020-09-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(verbose_name='Trang thái'),
        ),
    ]
