# Generated by Django 3.1 on 2020-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200924_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='Ảnh'),
        ),
    ]
