# Generated by Django 3.1 on 2020-09-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200924_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(verbose_name='trạng thái'),
        ),
    ]
