# Generated by Django 3.1 on 2020-09-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200930_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesproduct',
            name='main_image',
            field=models.ImageField(default=None, upload_to='static/images/', verbose_name='ảnh chính'),
        ),
        migrations.AlterField(
            model_name='imagesproduct',
            name='image',
            field=models.ImageField(upload_to='static/images/', verbose_name='ảnh chi tiết'),
        ),
    ]
