# Generated by Django 3.1 on 2020-09-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200930_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesproduct',
            name='main_image',
        ),
    ]
