# Generated by Django 3.1 on 2020-09-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_imagesproduct_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesproduct',
            name='main_image',
        ),
    ]
