# Generated by Django 3.1 on 2020-10-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_imagesproduct_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesproduct',
            name='main_image',
        ),
    ]
